### PR TITLE
fixed the sqflite_web return format to match was was being returned in sqflite

### PR DESCRIPTION
**Pull request by jamespet77**
I can't be sure this is 100% correct.  I am using jaguar orm and attempting to get this working with it.  jaguar uses sqflite and works great with it.  When I was pulling use the web version the formats were wrong and causing a lot of issues.  I just converted it to match the same format that jaguar was expecting from sqflite.  If this is wrong ignore it/.

### CODE REVIEW

**Comment by deakjahn** [comment]
Let's ping Alex @alextekartik to see what his opinion is.

**Comment by deakjahn** [comment]
@alextekartik Let's ping Alex to see what his opinion is.

**Comment by robinbonnes** [comment]
Edit: Sorry your correct @linuxjet. I can confirm this works. Can we merge this in?

**Comment by deakjahn** [comment]
If it works, we can for sure, the problem is that I had to fix an error yesterday and this made the two PR's conflict. Sorry... Could you update your side to be in sync once again?

**Comment by alextekartik** [comment]
For information, internally between the native and dart world in sqflite, query result data are coded as 'columns' and 'rows' for efficiency. The result is wrapped in a fake list of map (QueryResultSet):

https://github.com/tekartik/sqflite/blob/5cd8b1bc8e11dfe8b7485e20fb5c345e8431162f/sqflite_common/lib/src/collection_utils.dart#L21-L26

**Comment by jamespet77** [comment]
I merged in the other changes and it is ready for merge

**Comment by deakjahn** [comment]
But I'll convert the map and list initializations to the more idiomatic way also suggested by _pedantic_. :-)

**Comment by deakjahn** [comment]
As I see, GitHub now screws up the permissions when something is merged. Well, I try a different route.

**Comment by deakjahn** [comment]
Well, I'll still struggle with this, but in the meantime, let's discuss it because, while it works and it returns a nice object, it seems to go against what Alex mentioned above. And chances are other parts of the Sembast packages might still expect that format.

**Comment by deakjahn** [comment]
I mention it here because some you might be fortunate enough to have that experience and might help out? Since this merge (even after reverting and doing it manually instead) I keep getting "insufficient permission for adding an object to repository database .git/objects" errors. All Google hits seem to imply Linux groups and access rights and therefore list the commands to fix that but I'm on Windows with an Android Studio, using the integrated Git solution. Not a problem with the system because other projects commit peacefully. Any good ideas, by any chance? :-)

**Pull request merged**
